events {

}

http {
    upstream backend {
        server gateway1:8000;  #container url:port - not local url:port
        server gateway2:8000;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend; #here backend is variable name
        }
    }
}

# for now nginx have 2 gateways to balance load
# nginx server balance load using round robin algorithm, send 1st request on gateway 1, 2nd request on gateway2, 3rd request on gateway1 again.