# boilercode of nginx
events{

}

http {
    upstream backend {  #create variable 'backend' here we write all server urls except load balancer.
        server server1:7000;
        server server2:7000;
        server server3:7000;
    }

    server {
        listen 80;   #server listing port
        # write custom logic for '/' route - load balance
        location /{
            proxy_pass http://backend;
        }
    }
}